import Head from 'next/head';
import {useState} from "react";
import {Button} from "@/components/button";
import {Dialog} from "@/components/dialog";

export default function Home() {
  const [opened, setOpened] = useState(false);

    return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app'/>
        <link rel='icon' href='/favicon.ico'/>
      </Head>
      <main>
        <Button handler={() => setOpened(true)}>Открыть</Button>
        <Dialog opened={opened} onClose={() => setOpened(false)}>
          <div>Hello!</div>
          <br/><br/>
          <Button handler={() => setOpened(false)}>Закрыть</Button>
        </Dialog>
      </main>
    </div>
  )
}
