import Head from 'next/head';
import {Layout} from "../layout";
import {ToDoList} from "@/components/toDoList";

export default function Home() {
    return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app'/>
        <link rel='icon' href='/favicon.ico'/>
      </Head>
      <Layout>
        <div className={'container'}>
          <ToDoList defaultTasks={[
            {ID: 1, name: 'Task 1', tags: [{ID: 1, value: 'frontend'}]},
            {ID: 2, name: 'Task number 2', tags: [{ID: 1, value: 'frontend'}, {ID: 2, value: 'backend'}]},
            {ID: 3, name: 'Task 3', tags: [{ID: 1, value: 'backend'}]}
          ]}/>
        </div>
      </Layout>
    </div>
  )
}
