import Head from 'next/head';
import {Layout} from "../layout";
import ToDoList from "@/components/toDoList/ToDoList";

export default function Home() {
    return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app'/>
        <link rel='icon' href='/favicon.ico'/>
      </Head>
      <Layout>
        <div className={'container'}>
          <ToDoList />
        </div>
      </Layout>
    </div>
  )
}
